### ISSUE TITLE
 fail to change the button text of an input file element

### ISSUE THREAD

**Issue by tarcia** [datchung/jquery.inputFileText#1]
Hello,

I tried this plugin just as the example given, but still can't change the button wordings to "select file".
Could you please kindly check for me  ?
Thanks a lot !
![html](https://cloud.githubusercontent.com/assets/17218370/16764103/d6be6328-485e-11e6-9d1b-23066460b727.jpg)
![see from web](https://cloud.githubusercontent.com/assets/17218370/16764104/d6bf8460-485e-11e6-90fe-b740230890c1.jpg)

**Comment by datchung** [comment]
Hi, here is a live example of how to use this plugin:
https://jsfiddle.net/fvw8L1qx/

Also, try moving the  `<script>$('#choose-file')...</script>` below the `<input type="file"... />`.
